# config.py

import torch

# --- Core Benchmark Configuration ---

# List of Hugging Face model identifiers or NeMo model names
MODELS_TO_BENCHMARK = [
    #"facebook/wav2vec2-base-960h",
    #"facebook/hubert-large-ls960-ft",
    #"openai/whisper-large-v3",
    #"nvidia/parakeet-tdt-0.6b-v2",
    "adas2t-meta-learner", # Add the meta-learner here
]

# List of datasets to evaluate on
# Each entry is a tuple: (dataset_name, configuration_dictionary)
DATASETS_INFO = [
    ("mozilla-foundation/common_voice_16_1", {"split": "test", "field": "sentence", "lang_config": "en"}),
    ("openslr/librispeech_asr", {"split": "test.clean", "field": "text"}),
    ("edinburghcstr/ami", {"split": "test", "config": "ihm", "field": "text"}),
    ("edinburghcstr/ami", {"split": "test", "config": "sdm", "field": "text"}),
    ("distil-whisper/earnings22", {"split": "test", "field": "transcription", "lang_config": "chunked"}),
    ("facebook/voxpopuli", {"split": "test", "field": "raw_text", "lang_config": "en_accented"}),
    ("google/fleurs", {"split": "test", "field": "transcription", "lang_config": "en_us"}),
]

# --- General Settings ---

# Use GPU if available, otherwise fall back to CPU
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"
TORCH_DTYPE = torch.float16 if torch.cuda.is_available() else torch.float32

# Number of samples to process from each dataset.
# Set to None to process the entire dataset.
NUM_SAMPLES = 100

# Path to save the final results
RESULTS_CSV_PATH = "asr_benchmark_results.csv"
PLOT_OUTPUT_PATH = "asr_benchmark_plot.png"


# --- ADAS2T Meta-Learner Configuration ---

# Paths to the pre-trained meta-learner model and associated files.
# These files are generated by running `train_metaleaner.py`.
ADAS2T_MODEL_PATH = "adas2t_model_ast.pth"
ADAS2T_SCALER_PATH = "adas2t_scaler.pkl"
ADAS2T_ALGORITHMS_PATH = "adas2t_algorithms.pkl"

# The pool of models that the ADAS2T handler will load and choose from at runtime.
# This MUST match the `algorithm_pool_models` list in `train_metaleaner.py`.
ADAS2T_ALGORITHM_POOL = [
    "facebook/hubert-large-ls960-ft",
    "facebook/wav2vec2-base-960h",
    "nvidia/parakeet-tdt-0.6b-v2",
]